import { ref } from 'vue'

export const activeMenu = ref(null)

export const massNewsCategory = ref([
  {
    key: 0,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'New',
  },
  {
    key: 1,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'New',
  },
  {
    key: 2,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'New',
  },
  {
    key: 3,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'New',
  },
  {
    key: 4,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Popular',
  },
  {
    key: 5,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Popular',
  },
  {
    key: 6,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Popular',
  },
  {
    key: 7,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Politics',
  },
  {
    key: 8,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Politics',
  },
  {
    key: 9,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Politics',
  },
  {
    key: 10,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Politics',
  },
  {
    key: 11,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Politics',
  },
  {
    key: 12,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Economy',
  },
  {
    key: 13,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Economy',
  },
  {
    key: 14,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Society',
  },
  {
    key: 15,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Society',
  },
  {
    key: 16,
    image: '../News/img-new-1.jpg',
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    category: 'Society',
  },
  {
    key: 17,
    image: '../News/img-new-1.jpg',
    label: 'Экзамен',
    date: '08.04.2025',
    views: '115',
    like: '19',
    category: 'Economy',
  },
])

export const menuItems = ref([
  {
    id: 'Finance',
    name: 'Финансы',
  },
  {
    id: 'Family',
    name: 'Семья',
  },
  {
    id: 'Politics',
    name: 'Политика',
  },
  {
    id: 'World',
    name: 'Мир',
  },
  {
    id: 'Showbiz',
    name: 'Шоубиз',
  },
  {
    id: 'Society',
    name: 'Общество',
  },
  {
    id: 'Sport',
    name: 'Спорт',
  },
  {
    id: 'Economy',
    name: 'Экономика',
  },
])

export const massSidebarPopularNews = [
  {
    key: 0,
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    isEnd: false,
  },
  {
    key: 1,
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    isEnd: false,
  },
  {
    key: 2,
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    isEnd: false,
  },
  {
    key: 3,
    label: 'Какие пенсионные изменения ждут россиян в 2025 году',
    date: '08.04.2025',
    views: '495',
    like: '109',
    isEnd: false,
  },
  {
    key: 4,
    label: 'Экзамен NKZU 2025 года',
    date: '20.05.2025',
    views: '1',
    like: '0',
    isEnd: true,
  },
]
